name: sc-mini
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - scanpy>=1.10
      - anndata>=0.10
      - numpy
      - pandas
      - matplotlib
      - scipy
      - scikit-learn
      - scrublet

